apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staywell-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - dev.staywell.com
    secretName: staywell-dev-tls
  rules:
  - host: dev.staywell.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-staywell-frontend-service
            port:
              number: 80
