apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: roomio-development

namespace: roomio-dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development
  app.kubernetes.io/instance: roomio-dev

images:
<<<<<<< HEAD
- name: ghcr.io/pablodelarco/staywell-manager-e301a7db
  newTag: sha-99d1d0f
=======
- name: ghcr.io/pablodelarco/roomio
  newTag: sha-0eac021
>>>>>>> c294379 (Remove all TLS-related files - Cloudflare handles SSL termination)

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml

replicas:
- name: roomio-frontend
  count: 1
