apiVersion: v1
kind: Service
metadata:
  name: staywell-frontend-service
spec:
  type: NodePort  # Keep NodePort for development access
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
