apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roomio-prod
  namespace: argocd
  labels:
    app: roomio
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/pablodelarco/Roomio
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: roomio-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
