apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staywell-manager-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: staywell-manager
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/staywell-manager-gitops
    targetRevision: HEAD
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: staywell-manager
  syncPolicy:
    # Manual sync for production - require approval
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
