apiVersion: apps/v1
kind: Deployment
metadata:
  name: staywell-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_DEBUG_MODE
          value: "false"
        - name: VITE_LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
