apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: staywell-production

namespace: staywell-manager

resources:
- ../../base
- hpa.yaml
- pdb.yaml

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- configmap-patch.yaml

images:
- name: ghcr.io/your-username/staywell-manager
  newTag: main-latest

replicas:
- name: staywell-frontend
  count: 3
