apiVersion: apps/v1
kind: Deployment
metadata:
  name: staywell-frontend
  labels:
    app: staywell-frontend
    app.kubernetes.io/name: staywell-frontend
    app.kubernetes.io/part-of: staywell-manager
spec:
  replicas: 1  # Will be overridden by overlays
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: staywell-frontend
  template:
    metadata:
      labels:
        app: staywell-frontend
        app.kubernetes.io/name: staywell-frontend
        app.kubernetes.io/part-of: staywell-manager
    spec:
      containers:
      - name: frontend
        image: ghcr.io/pablodelarco/staywell-manager-e301a7db:latest  # Will be overridden
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user
        fsGroup: 101
