apiVersion: apps/v1
kind: Deployment
metadata:
  name: staywell-frontend
  labels:
    app.kubernetes.io/name: staywell-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: staywell-platform

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: staywell-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: staywell-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: staywell-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101

      containers:
      - name: frontend
        image: ghcr.io/pablodelarco/staywell-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: staywell-config
              key: environment
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: staywell-secrets
              key: supabase-url
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: staywell-secrets
              key: supabase-anon-key

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
