apiVersion: v1
kind: Secret
metadata:
  name: staywell-secrets
  labels:
    app.kubernetes.io/name: staywell-manager
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: staywell-platform
type: Opaque
data:
  # Base64 encoded secrets - REAL VALUES
  # Use: echo -n "your-value" | base64
  supabase-url: aHR0cHM6Ly90ZGRmdWJkYnJtY3RlY2xycG5mdi5zdXBhYmFzZS5jbw==  # https://tddfubdbrmcteclrpnfv.supabase.co
  supabase-anon-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5Sa1pHWjFZbVJpY20xamRHVmpiSEp3Ym1aMklpd2ljbTlzWlNJNkltRnVibTRpTENKcFlYUWlPakUzTlRRNE5EVXpPREFzSW1WNGNDSTZNakEzTURReU1UTTRNSDAua0hZTnctMlBJaS1DZzVlT3hQWUV4YjFDY25mY0ZvcU9DR2lNaXpDWkpQWQ==  # your-anon-key
  
  # Future secrets for SaaS features
  stripe-publishable-key: cGtfdGVzdF95b3VyLXN0cmlwZS1rZXk=  # pk_test_your-stripe-key
  sentry-dsn: aHR0cHM6Ly95b3VyLXNlbnRyeS1kc24=  # https://your-sentry-dsn
