apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-tls-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-tls-config
    app.kubernetes.io/part-of: staywell-manager
data:
  tls.yaml: |
    tls:
      options:
        # Modern TLS configuration (TLS 1.3 only)
        modern:
          minVersion: "VersionTLS13"
          cipherSuites:
            - "TLS_AES_256_GCM_SHA384"
            - "TLS_CHACHA20_POLY1305_SHA256"
            - "TLS_AES_128_GCM_SHA256"
          curvePreferences:
            - "X25519"
            - "secp384r1"
          sniStrict: true
          
        # Intermediate TLS configuration (TLS 1.2+)
        intermediate:
          minVersion: "VersionTLS12"
          maxVersion: "VersionTLS13"
          cipherSuites:
            # TLS 1.3 ciphers
            - "TLS_AES_256_GCM_SHA384"
            - "TLS_CHACHA20_POLY1305_SHA256"
            - "TLS_AES_128_GCM_SHA256"
            # TLS 1.2 ciphers
            - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
            - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
            - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          curvePreferences:
            - "X25519"
            - "secp384r1"
            - "secp256r1"
          sniStrict: true
          
        # Default secure configuration
        default:
          minVersion: "VersionTLS12"
          cipherSuites:
            - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
            - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
            - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          curvePreferences:
            - "secp384r1"
            - "secp256r1"
