// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tddfubdbrmcteclrpnfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZGZ1YmRicm1jdGVjbHJwbmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDUzODAsImV4cCI6MjA3MDQyMTM4MH0.kHYNw-2PIi-Cg5eOxPYExb1CcnfcFoqOCGiMizCZJPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});