name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --audit-level moderate

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet package*.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated npm dependencies to latest compatible versions
            - Applied security fixes where available
            
            ### Testing
            - [ ] Verify application builds successfully
            - [ ] Test core functionality
            - [ ] Check for any breaking changes
            
            **Note**: This PR was created automatically. Please review changes before merging.
          branch: chore/dependency-updates
          delete-branch: true
