apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staywell-tls
spec:
  secretName: staging-staywell-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - staging.pablodelarco.com
  usages:
  - digital signature
  - key encipherment
