apiVersion: apps/v1
kind: Deployment
metadata:
  name: staywell-frontend
spec:
  template:
    spec:
      # Staging: Remove node selector for better distribution
      nodeSelector: {}
      containers:
      - name: frontend
        env:
        - name: NODE_ENV
          value: "production"
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "64Mi"  # Production-like resources
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
